# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20180321_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojo',
            new_name='dojo_id',
        ),
    ]
